"""Adding meeting info

Revision ID: 330bd031b6e3
Revises: 39a5be40d7b0
Create Date: 2012-10-23 20:34:28.783186

"""

# revision identifiers, used by Alembic.
revision = '330bd031b6e3'
down_revision = '39a5be40d7b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('meeting_info', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'meeting_info')
    ### end Alembic commands ###
