"""updating account table

Revision ID: 446844b3915b
Revises: ebcad8b0948
Create Date: 2013-10-23 21:51:28.849084

"""

# revision identifiers, used by Alembic.
revision = '446844b3915b'
down_revision = 'ebcad8b0948'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'beaker_cache')
    op.add_column('users', sa.Column('auth_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('identifier', sa.String(), nullable=True))
    op.drop_column('users', u'access_token')
    op.drop_column('users', u'access_token_secret')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'access_token_secret', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column(u'access_token', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'identifier')
    op.drop_column('users', 'auth_token')
    op.drop_column('users', 'auth_secret')
    op.create_table(u'beaker_cache',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('beaker_cache_id_seq'::regclass)", nullable=False),
    sa.Column(u'namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column(u'accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column(u'created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column(u'data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'id', name=u'beaker_cache_pkey')
    )
    ### end Alembic commands ###
