"""adding versions

Revision ID: 465824c62317
Revises: 55335e6da002
Create Date: 2013-10-24 21:35:08.654350

"""

# revision identifiers, used by Alembic.
revision = '465824c62317'
down_revision = '55335e6da002'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('mailing_list', sa.String(), nullable=True),
    sa.Column('meeting_info', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('updated_ts', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('companies_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('updated_ts', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.add_column(u'companies', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column(u'groups', sa.Column('version', sa.Integer(), nullable=True))

    op.execute("update companies set version=0")
    op.execute("update groups set version=0")

    op.alter_column("companies", "version", nullable=False)
    op.alter_column("groups", "version", nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'groups', 'version')
    op.drop_column(u'companies', 'version')
    
    op.drop_table('companies_history')
    op.drop_table('groups_history')
    ### end Alembic commands ###
