"""moving email field

Revision ID: 55335e6da002
Revises: 446844b3915b
Create Date: 2013-10-24 20:01:59.483394

"""

# revision identifiers, used by Alembic.
revision = '55335e6da002'
down_revision = '446844b3915b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('users', u'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'email', sa.VARCHAR(), nullable=True))
    op.drop_column('profiles', 'email')
    ### end Alembic commands ###
