"""user to history columns

Revision ID: 55f1aa3a14e1
Revises: 465824c62317
Create Date: 2013-10-24 22:19:42.516020

"""

# revision identifiers, used by Alembic.
revision = '55f1aa3a14e1'
down_revision = '465824c62317'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('groups_history', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups_history', 'user_id')
    op.drop_column('companies_history', 'user_id')
    ### end Alembic commands ###
