"""company membership

Revision ID: ebcad8b0948
Revises: ba0f86ee67c
Create Date: 2012-11-02 20:56:05.044942

"""

# revision identifiers, used by Alembic.
revision = 'ebcad8b0948'
down_revision = 'ba0f86ee67c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_employees',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_employees')
    ### end Alembic commands ###
